### ISSUE TITLE
docker-compose to self host this please?

### ISSUE THREAD

**Issue by xxdesmus** [louislva/skyline#3]
Any chance we can self host this via a simple docker-compose?

**Comment by louislva** [comment]
I think that would be great! Rn I don't have time but it would be absolutely blessed if you could do it? Basically all it is, is a Postgres database (schema defined in db.sql), the Next.js server (npm install & npm build & npm start), and then creating a .env.local with a DATABASE=[postgres connection string] & the openai token in there as well!

**Comment by louislva** [comment]
I think a docker-compose would be huge both for self-hosting & ease of development!

**Comment by potatoqualitee** [comment]
Lez see if I can get this going with a Dev Container
